# Generated by Django 5.0.6 on 2024-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_items_img/'),
        ),
        migrations.DeleteModel(
            name='GalleryItemsImg',
        ),
    ]
